### ISSUE TITLE
HS2FCL parallel execution increases computation time

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#101]
@chrMongeau in the [comment on #97](https://github.com/SWS-Methodology/faoswsTrade/issues/97#issuecomment-284723608)
> `esdata <- esdata %>% mapHS2FCL(hsfclmap, multicore)`
>  it is taking a very long time (around 20 minutes so far; I see that the cores are working as there are 8, i.e., the number of cores, Rscript.exe processes running). If multicore is FALSE the same computation takes around five minutes.
> @malexan could you tell me how it much takes for you mapHS2FCL() on both esdata and tldata with multicore = TRUE and multicore = FALSE?

**Comment by malexan** [comment]
Eurostat mapping with parallel execution takes about 5 minutes.

```
DEBUG [2017-03-08 10:37:16] Multicore backend is available.
DEBUG [2017-03-08 10:37:16] CPU cores detected: 4.
INFO [2017-03-08 10:38:30] Records after removing areas absent in HS->FCL map: 982135
[2691] Convert Eurostat HS to FCL
INFO [2017-03-08 10:43:12] Records after HS-FCL mapping: 982135
```

**Comment by malexan** [comment]
Eurostat no parallel 8 minutes. (Probably it is not honest estimation, as I got 5 minutes on batteries, and 8 minutes on socket) 

```
INFO [2017-03-08 11:10:05] Records after removing areas absent in HS->FCL map: 982135
[3559] Convert Eurostat HS to FCL
INFO [2017-03-08 11:18:16] Records after HS-FCL mapping: 982135
```

I will report about Tariffline timing after merging of `extendreport`, where it is included in the logging.

**Comment by chrmongeau** [comment]
It seems that this was something from my side, as I just run the module again (with 30696fd included) and it now requires nearly 2 minutes with `multicore = TRUE` and almost 6 minutes with `multicore = FALSE`.

Given that it was not a real bug in the code but something on my machine, I close this issue.
