### ISSUE TITLE
NormalizePath() on reportdir

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#107]
It would be nice (and useful) to have `reportdir` defined with forward slashes. (Probably this is something specific only to Windows.)

Right now, it is like:

```
> reportdir
[1] "C:\\Users\\mongeau\\AppData\\Local\\Temp\\Rtmp4ojPXc/mongeau/complete_tf_cpc_20170309133916CET"
```

If I copy the path, paste it on file explorer and press Enter, the directory can't be found because of the double backslashes. To avoid this, `NormalizePath()` can be used to define `reportdir`:

```
> normalizePath(reportdir, winslash='/')
[1] "C:/Users/mongeau/AppData/Local/Temp/Rtmp4ojPXc/mongeau/complete_tf_cpc_20170309133916CET"
```

**Comment by malexan** [comment]
Hm, I built `reportdir` with `file.path()` function, what cares about OS-specific slashes. So is the problem in "R_SWS_SHARE_PATH" value?

```r
reportdir <- file.path(
  Sys.getenv("R_SWS_SHARE_PATH"),
  USER,
  paste0("complete_tf_cpc_",
format(Sys.time(), "%Y%m%d%H%M%S%Z")))
```

There is a call to `browseURL` in master branch:

```r
# Open report directory in system default file browser
if(interactive()) browseURL(reportdir)
```

In Linux it opens the report directory with file browser. Does it works in Windows?

**Comment by chrmongeau** [comment]
The file path is perfectly set (i.e., R can write on the file). I meant that if at at some later point I want to open the file, I have to print the `reportdir` variable and replace `\\` with `\` or `/` in order to be able to put it in the file explorer and open the directory without issues (if I leave `\\` Windows doesn't find the location).

> In Linux it opens the report directory with file browser. Does it works in Windows?

Yes it does.

**Comment by malexan** [comment]
> Right now, it is like:
> ```
> > reportdir
> [1] "C:\\Users\\mongeau\\AppData\\Local\\Temp\\Rtmp4ojPXc/mongeau/complete_tf_cpc_20170309133916CET"
> ```

In this your example masked slashes are in `R_SWS_SHARE_PATH` part. Can you show your `R_SWS_SHARE_PATH`? When you copy only it and paste in the File Explorer, does it work?

**Comment by chrmongeau** [comment]
> Can you show your `R_SWS_SHARE_PATH`? 

I don't have defined a `R_SWS_SHARE_PATH` environment variable. I'll reformulate the suggestion in #109.

**Comment by malexan** [comment]
But how your `reportdir` was built?
> ```
> > reportdir
> [1] "C:\\Users\\mongeau\\AppData\\Local\\Temp\\Rtmp4ojPXc/mongeau/complete_tf_cpc_20170309133916CET"
```

**Comment by chrmongeau** [comment]
By setting `R_SWS_SHARE_PATH` [here](https://github.com/SWS-Methodology/faoswsTrade/blob/be32db472ced7382ed724801ebabbe8a306003c4/modules/complete_tf_cpc/main.R#L108), like this:

` Sys.setenv("R_SWS_SHARE_PATH" = tempdir())`

**Comment by malexan** [comment]
Hm, it means `tempdir()` and `file.path()` use different approaches to slashes, right?

Can you (just for theoretical interest) show your output for this:
```r
tempdir()
file.path(tempdir(), "bar", "bar2")
```

On my Linux it looks like that:
```r
> tempdir()
[1] "/tmp/RtmpObBrKg"
> file.path(tempdir(), "bar", "bar2")
[1] "/tmp/RtmpObBrKg/bar/bar2"
```

**Comment by chrmongeau** [comment]
```r
> tempdir()
[1] "C:\\Users\\mongeau\\AppData\\Local\\Temp\\Rtmp8ukplm"
> file.path(tempdir(), "bar", "bar2")
[1] "C:\\Users\\mongeau\\AppData\\Local\\Temp\\Rtmp8ukplm/bar/bar2"
```
