### ISSUE TITLE
Set R_SWS_SHARE_PATH when not on the server

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#109]
When `faosws::CheckDebug() == TRUE` (i.e., when _not_ on the server), the R_SWS_SHARE_PATH is never set. It should be done by

`R_SWS_SHARE_PATH <- SETTINGS[["share"]]`

where `SETTINGS[["share"]]` can be found in the `sws.yml` file (all: share).

**Comment by malexan** [comment]
I already have something on the topic in `extendreport` branch [here](https://github.com/SWS-Methodology/faoswsTrade/blob/63e7892943ac037adc610bd39ec3d662a572ac5d/modules/complete_tf_cpc/main.R#L102-L108). 

```r
  # Fall-back R_SWS_SHARE_PATH var
  if(is.na(Sys.getenv("R_SWS_SHARE_PATH", unset = NA))) {
    flog.debug("R_SWS_SHARE_PATH system variable not found.")
    Sys.setenv("R_SWS_SHARE_PATH" = tempdir())
    flog.debug("R_SWS_SHARE_PATH now points to R temp directory %s",
               tempdir())}
} else {
```

**Comment by malexan** [comment]
So `SETTINGS[["share"]]` instead of `tempdir()`?

**Comment by chrmongeau** [comment]
Your fallback is OK, but the point is that the variable is never set before. Thus, I'd say that the module should try to use `SETTINGS[["share"]]` and if doesn't exist, then use the fallback.

**Comment by chrmongeau** [comment]
> Thus, I'd say that the module should try to use SETTINGS[["share"]] and if doesn't exist, then use the fallback.

Given that a `R_SWS_SHARE_PATH` environment variable should/could be set, maybe the module should try: 1) to use it; 2) if not found, use `SETTINGS[["share"]]`; 3) use the `tempdir()` fallback (considering #107).
