### ISSUE TITLE
Read hs6faointerest from SWS

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#110]
Currently the `complete_tf_cpc` module [reads the `hs6faointerest` table from the package itself](https://github.com/SWS-Methodology/faoswsTrade/blob/1d61cc65ed7e86b65e73c6f163ca74c0ecc67e2e/R/getAgriHSCodes.R#L11). It'd be better to read it from a datatable on SWS.

**Comment by malexan** [comment]
Do datasets unsdpartnersblocks, fclunits, comtradeunits, EURconversionUSD have the similar problem? They are loaded like this:

```r
data("fclunits", package = "faoswsTrade", envir = environment())
#fclunits <- tbl_df(ReadDatatable("fclunits"))
```
Does this comment mean that `fclunits` data set exists in SWS?

**Comment by chrmongeau** [comment]
> Do datasets unsdpartnersblocks, fclunits, comtradeunits, EURconversionUSD have the similar problem?

Yes, they should be read from SWS (see #24). I will see what datasets are not yet converted and/or loaded on SWS.

> Does this comment mean that fclunits data set exists in SWS?

Yes, though they differ on a variable type and the presence of an attribute:

```
> fclunits_sws <- tbl_df(ReadDatatable("fclunits"))
> data("fclunits", package = "faoswsTrade", envir = environment())
> str(fclunits_sws)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':       614 obs. of  2 variables:
 $ fcu_fcl    : chr  "15" "16" "17" "18" ...
 $ fcu_fclunit: chr  "mt" "mt" "mt" "mt" ...
 - attr(*, ".internal.selfref")=<externalptr> 
> str(fclunits)
'data.frame':   614 obs. of  2 variables:
 $ fcl    : int  15 16 17 18 19 20 21 22 23 24 ...
 $ fclunit: chr  "mt" "mt" "mt" "mt" ...
```

Besides these two differences, contents are the same.

**Comment by chrmongeau** [comment]
@malexan The `hs6faointerest` table is now read from SWS as a `data.table` with one column named `hs6_code`:

```r
> hs6faointerest <- faosws::ReadDatatable('hs6faointerest')
> hs6faointerest
     hs6_code
  1:    10121
  2:    10129
  3:    10130
  4:    10190
  5:    10221
 ---         
736:   530290
737:   530310
738:   530390
739:   530500
740:   530810
> str(hs6faointerest)
Classes ‘data.table’ and 'data.frame':  740 obs. of  1 variable:
 $ hs6_code: chr  "10121" "10129" "10130" "10190" ...
 - attr(*, ".internal.selfref")=<externalptr> 
```

**Note**: the table is smaller as it was originally given that duplicate values were removed.

**Comment by chrmongeau** [comment]
@malexan The `getAgriHSCodes()` is now reading again the data from SWS, so you need to have a data table like:

```
> hs6faointerest <- faosws::ReadDatatable('hs6faointerest')
> hs6faointerest
       hs6_code
    1:   010100
    2:   010101
    3:   010102
    4:   010103
    5:   010104
   ---         
21348:   530596
21349:   530597
21350:   530598
21351:   530599
21352:   530810
```
