### ISSUE TITLE
Do we want report content to be sent to R console?

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#111]
@chrMongeau What do you think? The console looks too messy after it. Probably just text file `report.txt` plus csv files is enough. Either we can do a setting to switch off report output to console?

I would prefer to have in R console technical info.

**Comment by chrmongeau** [comment]
Yes, a setting to switch off report output to console would be great.

**Comment by malexan** [comment]
@chrMongeau, now there is `general_log2console = FALSE`. So all analytical tables and messages go only to files by default. We have two loggers, the first one (default) is for analytical stuff, and the second one with name `dev` is for messages on technical issues.

If you want to add analytical (or client/user, - how to call it?) logging message you use default logger:

```r
flog.info("My message for B/C team")
```
In this case you send `My message for B/C team` to `report.txt`.

If you want to get message to console and to `development.log` file, you use the following:
```r
flog.info("My message for geeks", name = "dev")
```

Let me know if you want anything else or need more details.

**Comment by chrmongeau** [comment]
@malexan OK, it's clear.
