### ISSUE TITLE
HSagric_filter should be used instead of HS2012 to filter raw trade data by HS codes of FAO interest

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#112]
Currently we use a list of HS codes from `HS2012-6 digits Standard.xls` to filter raw trade data. But based on Katherina's message `HSagric_filter` should be used instead:

> Many of the codes in the attached spreadsheets (both TL and ES sheets) should have been discarded by applying the filters we had previously shared with Team A
> +(please see the spreadsheet in the attached email from March 2016 for details on which codes should be filtered out).

**Comment by malexan** [comment]
@chrMongeau I've done. `extendreport` is merged with this branch also.

**Comment by malexan** [comment]
Module run with HSagric_filter and full reporting included (csv is not supported in GitHub comments).
[report.txt](https://github.com/SWS-Methodology/faoswsTrade/files/844143/report.txt)

**Comment by chrmongeau** [comment]
This can be closed: the codes of interest are now read into:

```r
hs6faointerest <- faosws::ReadDatatable('hs6faointerest')
```

The column `hs6_code` contains all the codes from `FromCode` to `ToCode` of the [HSagric_filter.xls](https://github.com/SWS-Methodology/faoswsTrade/blob/fc9de9e8c782e6a6f2e8b624ef2162e8f2a93623/data-raw/HSagric_filter.xls) file.
