### ISSUE TITLE
Include main.R into faoswsTrade package installation to have both stable and development version of it 

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#118]
Currently I run `main.R` file directly from a  folder with faoswsTrade package source code. As module run takes time, meanwhile I would like to continue to edit the code or to switch to other git-branches. But I don't like the idea of editing file while it is evaluated by R.

@sebastian-c Is it possible to include `modules/*/main.R` file in the package bundle? In this case I would source the module's 'main.R' from package installation directory and edit files in other place. 

Currently `main.R` is not part of installed R package, right?

```
ls ~/R/x86_64-redhat-linux-gnu-library/3.3/faoswsTrade/
data  DESCRIPTION  help  html  INDEX  Meta  NAMESPACE  NEWS.md  R
```

Maybe hard/symbolic link from `inst` directory? Or to specify somewhere to include `modules` folder in the package?

**Comment by sebastian-c** [comment]
Modules are kept intentionally separate from the package. The package is a source of functions while the module contains code which depends on the package.

I'm not sure that editing a file being evaluated by R is a problem. The R script should be fine, the only problem you might have is if the R script reads secondary files. To demonstrate this, try a script with the following:

```r
Sys.sleep(10)
"I ran even though the script was edited"
```
Source it. While it's running, replace and save:

```r
"I replaced what was going to be run"
```

**Comment by malexan** [comment]
OK, thank you Sebastian!
