### ISSUE TITLE
HS digits in CSV should show leading zero

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#120]
HS are not shown correctly in CSV files, when opening them in Excel. For example:

```
"reporter","flow","datumid","hs","hsext","fcl","recordnumb","name"
12,1,24898,"01012100",1012100,NA,NA,"Bahamas"
12,1,24906,"01051500",1051500,NA,NA,"Bahamas"
```

will be displayed as

```
reporter flow datumid      hs   hsext fcl recordnumb    name
      12    1   24898 1012100 1012100  NA         NA Bahamas
      12    1   24906 1051500 1051500  NA         NA Bahamas
```

(Notice how leading zeros were removed in column `hs`.)

While not strictly a bug (this is Excel's fault that presumes that what seems like a number is a number), I'm putting a "bug" label as end-users are confused by this.

Probably, a leading character should be added at the beginning of strings that could have a leading zero.

**Comment by malexan** [comment]
[There](https://superuser.com/a/527894) is a workaround for Excel/Calc:

> Excel → Data → Get external data → Select all columns with __Shift__ and choose `Text`

As for programming part, our CSV-writer could do the [following](http://stackoverflow.com/a/165052):

> `"=""2008-10-03"""`

**Comment by chrmongeau** [comment]
This was solved by adding a "chapter" column next to the hs code: if chapter is 1 then the "10101" code in the CSV is supposed to be actually "010101", etc.
