### ISSUE TITLE
Load/transform esdata and tldata ASAP

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#136]
We probably should load `esdata` and `tldata` as soon as possible and do some minimal transformations (i.e., `adaptTradeDataNames()`, `adaptTradeDataTypes()`) in order to generate the pre-processing reports and then add a parameter to stop the module if only these reports are required.

**Comment by chrmongeau** [comment]
@malexan @vidigal88 what do tou think?

**Comment by malexan** [comment]
I think it is not a problem, if we want reports on raw trade data in original area codes etc.

**Comment by chrmongeau** [comment]
@malexan I created the `issue136` branch where `esdata` and `tldata` are loaded at the beginning. It should work with the `rprt_rawtradedata()` function, but haven't checked: when is it used?

**Comment by malexan** [comment]
in `adaptTradeDataTypes`

**Comment by malexan** [comment]
Yep, it is faster now :)
