### ISSUE TITLE
Raw data reports

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#140]
We need reports on raw data. The suggested tables are (quoting Team B/C .doc):

- [x] **Table1**: "Country list by year of which reporters are contained in the file: A table such as this would allow us to quickly identify data gaps and facilitate comparisons. If we are only adding on year at a time, then obviously this table would only contain one column, but it would be helpful to compare it to previous years."
- [x] **Table 2**: "List of non-reporting countries: Same general format as above, but contains the complementary list of countries not reporting for those years (similar to your table 8)"
- [x] **Table 3**: "Number of records, by reporter (this is very similar to your table 7)"
- [x] **Table 4**: "Import/export content check: For every reporter for the year in question, a check that the file contains both import data and export data (as well as re-exports and re-imports). Each year would have its own table."
- [x] **Table 5**: "For each reporter, a comparison of the number of records, compared to the previous year."
- [x] **Table 6**: "Check that quantities and values are included, current year"
- [x] **Table 7**: "Report of records with missing quantities, for each year"
- [x] **Table 8**: "Listing of countries by year , for which data has been revised"
- [x] **Table 9**: "List of unmapped codes, by country, by year"

@malexan @vidigal88 Let's update this issue by indicating when the tables are generated/stored.

**Comment by chrmongeau** [comment]
I marked Table 8 as done, as it should probably be produced at harvesting stage (see comment in doc).

**Comment by malexan** [comment]
Table 9 is already prepared and passed to the team B/C, right?

**Comment by malexan** [comment]
I am working on 3, 5, 6, 7

**Comment by chrmongeau** [comment]
> Table 9 is already prepared and passed to the team B/C, right?

Right you are. I updated the list.

**Comment by vidigal88** [comment]
I'm working on 1, 2 and 4

**Comment by malexan** [comment]
There is a function `ts_preproc()` which extracts from the raw trade data the following per each year/reporter/flow:

* number of records;
* number of partners;
* number of non-numeric partners;
* number of non-numeric hs codes;
* number of missing values;
* number of missing quantities (weight AND qty);
* proportions of 4 previous items.

So it solves tables 3, 5, 6, 7.

Currently all these data are saved in a single csv file `ts_preproc_long_format.csv`. 

Opened issues here:

* If the client wants these tables separately they have to be split. 
* Not all country names in Tariffline part are available ( #137 will solve the problem).


```r
faoswsTrade:::ts_preproc("/mnt/storage/sws_share/sas", "complete_tf_cpc")
```
```
# A tibble: 779 x 14
   reporter         name  flow records_count partners nonmrc_prt nonmrc_hs
      <chr>        <chr> <chr>         <int>    <int>      <int>     <int>
 1      001       France     1         50382      213          0       789
 2      001       France     2        107269      231          0      1766
 3      003  Netherlands     1         41222      207          0      1131
 4      003  Netherlands     2         93213      234          0      1141
 5      004   Fr Germany     1         58961      206          0       937
 6      004   Fr Germany     2        127218      232          0      1272
 7      005        Italy     1         43581      189          0       741
 8      005        Italy     2         92548      222          0       895
 9      006 Utd. Kingdom     1         43431      204          0       797
10      006 Utd. Kingdom     2         73394      227          0       997
# ... with 769 more rows, and 7 more variables: novalue <int>, noqty <int>,
#   nonmrc_prt_prop <dbl>, nonmrc_hs_prop <dbl>, novalue_prop <dbl>,
#   noqty_prop <dbl>, year <int>
```

**Comment by malexan** [comment]
During the implementation of time series reports I imaged the following approach:

1. The module processes all years. It produces report directory per each year, including subdirectory with `rds` files (duplicates of csv).
2. The function `ts_all_reports` works with full collection of report directories and produces a bunch of csv files in `ts_reports` directory.

Internally `ts_all_reports` is just sequence of `ts_*` functions each of them produces specific time series report.

If you want to produce a new time series report you need to check is there suitable per-year report with required data. If not, than:

1. create such report (`rprt_mynewreport`);
2. add its call to `main.R` (or somewhere internally);
3. create time series report (`ts_mynewts_rprt`);
4. add its call to `ts_all_reports.R`. 

So after next iteration you will get it.

If you have suitable per-year tables, than you don't need steps 1 and 2.

**Comment by chrmongeau** [comment]
The module currently generates:

* Table_1_ts_reporters.csv
* Table_2_ts_non_reporters.csv
* Table_3_ts_preproc_long_format.csv
* Table_4_ts_check_content.csv
* Table_6_ts_flows_check.csv
* Table 9

**Comment by chrmongeau** [comment]
All reports have been created.
