### ISSUE TITLE
Disable progress bars when using the SWS

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsTrade#145]
The current implementation produces these huge progress bars. The logs have ballooned from less than 1MB to at least 50MB each. The main problem however is that they produce very large single lines that are hard to scroll past. I've managed to get around it somewhat by editing the log, but I'd rather avoid it. Is it possible to use CheckDebug() to check if you're on the working system and then use `progress_none()`?

However, I understand the need to know how far along a process is - are the existing logs that you have now sufficient or is it necessary to have the progress bars as well? Is it possible to divert the progress bar output?

**Comment by chrmongeau** [comment]
Done with 067b3fe.
