### ISSUE TITLE
Duplication of trade flows in Complete trade dataset

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/faoswsTrade#150]
We find duplicate series for products where corrections were made. For example, see the screenshot below. A correction was made for Netherlands imports of hop cones from USA. Then the USA series was duplicated into Ethiopia (data, flags, all), which before did not have a series.
![image](https://user-images.githubusercontent.com/31275016/29610016-37d67044-87f9-11e7-9f24-1de143b3ca22.png)

**Comment by chrmongeau** [comment]
This should not be related to the corrections. I will investigate this. Here is another example:

![image](https://user-images.githubusercontent.com/10231857/29611491-f624fdaa-87fd-11e7-8889-e80a4eb3b40b.png)

Comtrade says [the right partner is India](https://comtrade.un.org/api/get?max=500&type=C&freq=A&px=HS&ps=2015%2C2014%2C2013%2C2012%2C2011&r=360&p=699%2C100&rg=all&cc=100610):

![image](https://user-images.githubusercontent.com/10231857/29611528-1f5c2d56-87fe-11e7-860e-de46bc0d1bd3.png)

**Comment by chrmongeau** [comment]
Problem identified. In:

https://github.com/SWS-Methodology/faoswsTrade/blob/0fda5c9665aa09bf4746e239dea8c6fa013459f3/modules/complete_tf_cpc/main.R#L1205

(modified to deal with #34) the `partner` falling in the `FALSE` case should have been `partnerM49`.
