### ISSUE TITLE
Module mixes official and partner data in complete trade flows

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/faoswsTrade#151]
We have found that the module seems to be inserting random mirror trade flows into datasets of official reporters. This should not be the case...official trade data from reporters should not include mirror data series as well. This issue was documented for Angola (many products, but only milled rice is included here) and for beer in Australia.
![image](https://user-images.githubusercontent.com/31275016/29612340-32242292-8801-11e7-8e01-cbdb21548995.png)

![image](https://user-images.githubusercontent.com/31275016/29612444-9d9ec72a-8801-11e7-8945-310db2e9cd62.png)

**Comment by chrmongeau** [comment]
As I explained some time ago, if the module does not produce numbers for a given transaction it will keep previously computed numbers for that transaction (I still have to completely understand what are the advantages of this behaviour). This is exactly what is happenning in the case you report. If you have a look at the flows for Angola (I just saw the one from South Africa, I guess the other ones are similar), they say that they were produced by runs of the module in July (having a look at the "History" panel on SWS helps). Now, we were aware of this and made a small module that "refreshes" the complete dataset (by downloading all the possible combinations of reporters/partners/flows/commodities/years, setting them to BLANK, and them uploading them back to SWS). Why it wasn't done for the reported transactions is unclear to me. I will investigate.

**Comment by chrmongeau** [comment]
On hold waiting for a complete run of the module for all years on a clean dataset.

**Comment by chrmongeau** [comment]
@baldwinkl Could you confirm that this was fixed after the runs on a clean dataset?

**Comment by baldwinkl** [comment]
All instances of it previously noted were resolved. I will let you know if I find the problem again.

**Comment by chrmongeau** [comment]
As per the previous comment, it seems that the issue was fixed satisfactorily.
