### ISSUE TITLE
Insert analyst name in user history when they are responsible for a correction

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/faoswsTrade#152]
Currently, the program is writing back "Mongeau" as responsible for corrections into the SWS history. Corrections should instead be attributed to the analyst responsible for the correction.

**Comment by chrmongeau** [comment]
The history will be overwritten by the user who runs the module. I added a "Comment" metadata field where some useful information is stored (as the analyst name):

![image](https://user-images.githubusercontent.com/10231857/32108834-2538c906-bb33-11e7-9748-f87ddd599304.png)
