### ISSUE TITLE
Flags should not change to imputed if data is not corrected

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/faoswsTrade#156]
One of the features of the validation tool is that analysts can verify a quantity/value as being ok despite being an outlier. However, these values are currently being flagged as "imputations", although the quantities have not changed. In these cases, the flag should not change, but a note should be added to the history instead. See below example for Brazil exports of maize to the United States in 2011. The quantity is the same, yet the flag was changed when the corrections were applied.
![image](https://user-images.githubusercontent.com/31275016/29774307-5975a948-8c01-11e7-8ff2-375a8ce2f713.png)

**Comment by chrmongeau** [comment]
Ack. While the corrections routine works, it needs to handle better the various cases. This is somehow related to #152.

**Comment by chrmongeau** [comment]
This was fixed. Here's the same extraction as of 2017-10-27:

![image](https://user-images.githubusercontent.com/10231857/32108680-b291e90a-bb32-11e7-9770-779eb5d6f31e.png)
