### ISSUE TITLE
fcl2cpc2 should refer to a SWS table, and not to an internal one

### ISSUE THREAD

**Issue by marcosmilzo** [SWS-Methodology/faoswsTrade#16]

**Comment by sebastian-c** [comment]
This issue is related to SWS-Methodology/faoswsUtil#22.

**Comment by sebastian-c** [comment]
Now that we've closed the issue, we'll still have to wait until I release faoswsUtil. When I do, remember to change the import in the description to faosws greater than or equal to that version.
