### ISSUE TITLE
convertGeonom2FAO returns NA codes

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsTrade#18]
`convertGeonom2FAO` always returns NA as codes that were not converted. It should give unique and I can't think of a reason for it to return NA.

**Comment by marcosmilzo** [comment]
This still has to be test in the SWS. The edit of the code was done remotely, without the possibility to run it on the SWS. If the SQL query is correct, this can be closed.
In principle the query should just select records for which the `declarant` is numeric, without character. For sure there is the case in which the declarant is `EU`, which we won't process.
