### ISSUE TITLE
NAs introduced by coercion

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsTrade#19]
A warning message pops up in the main script at [line 299](https://github.com/SWS-Methodology/faoswsTrade/blob/master/modules/complete_tf_cpc/main.R#L299-L306):

```
Warning message:
In eval(substitute(expr), envir, enclos) : NAs introduced by coercion
```

It's only a warning, but it's worth investigating and silencing if there's nothing wrong. From experience, this usually causes headaches with data being removed.

**Comment by marcosmilzo** [comment]
Making some tests, it shows that there are records, in `tldata` (which is the UNSD trade data), in which the `hs` code presents two dots at the end (i.e. "2206009000.."). I never faced this, and I do not know if this is a problem when loading the data from the SWS within the module, or indeed some codes present the dots at the end. The code needs all the `hs` to be numeric. In case we have to remove them from the `ReadDatatable` directly.

**Comment by sebastian-c** [comment]
Of the 6M rows in `tldata$comm`, about 5000 have non-numeric characters in the code.

```
> tldata[!grepl("^[[:digit:]]+$", comm)]
      rep tyear flow         comm prt weight   qty qunit       tvalue chapter
   1:  97  2009    1     1516S431 840     NA    NA     1     69.69692      15
   2:  97  2009    2     50MMM000 899     NA    NA     1  82531.25992      50
   3:  97  2009    2     38SSS598 234     NA    NA     1    279.24635      38
   4:  97  2009    2     4002S232  68     NA    NA     1    153.58549      40
   5:  97  2009    2     38SSS999 410     NA    NA     1     27.92464      38
  ---                                                                        
4729: 686  2009    2 2208500000.. 837   5559  5559     8  45815.53087      22
4730: 686  2009    2 2208600000.. 466   1396  1396     8  12337.27601      22
4731: 686  2009    2 2208600000.. 837   4819  4819     8  33973.83047      22
4732: 686  2009    2 2208700000.. 466    561   561     8   4899.01284      22
4733: 686  2009    2 2208700000.. 837  14187 14187     8 110752.98142      22
```

Of these, 2100 end in `..`.
