### ISSUE TITLE
Run trade flow from 2009-2014

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsTrade#23]
I tried running it three times in a set of scheduled sessions, but I think the sessions got too big and slow. I'm starting again (again) and writing to the database one by one.

**Comment by sebastian-c** [comment]
Run:
- [ ] 2009
- [ ] 2010
- [ ] 2011
- [ ] 2012
- [ ] 2013
- [ ] 2014

Written:
- [ ] 2009
- [ ] 2010
- [ ] 2011
- [ ] 2012
- [ ] 2013
- [ ] 2014

**Comment by sebastian-c** [comment]
This is put on hold until #32 is resolved.

**Comment by chrmongeau** [comment]
Is this issue still open? (#32 was resolved.)

**Comment by sebastian-c** [comment]
I'm fairly sure that it was, but in any case, I imagine that changes have been made since and it will have to be re-run from 1990.

**Comment by chrmongeau** [comment]
AFAIK, this will not run for years < 2000, thus can be closed.

**Comment by chrmongeau** [comment]
(by "this will not run for years < 2000" I meant that we are interest only on running the module for years >= 2000)
