### ISSUE TITLE
Key not found for dimension measuredItemCPC

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsTrade#26]
There are a number of CPC codes that aren't in the destination table for Total trade. I'm not sure as to why that is, but among them are `01241.90`, `01919.96` and `21419.91`.

**Comment by marcosmilzo** [comment]
@sebastian-c is this still a open issue, after closing the dependency of the fcl2cpc?

**Comment by sebastian-c** [comment]
If the table has been fixed, quite possibly. I'll check before I close it.

**Comment by sebastian-c** [comment]
I'm making a complete list of all the CPC codes that the trade tables produce which are not in the destination table. Has the CPC conversion table been fixed?

**Comment by sebastian-c** [comment]
Here are all the codes that I have that are missing. I'll rerun the tradeflow data to pull in the correct CPC codes.

"21419.99" "21419.91" "01241.90" "01919.96" "39120.91" "02959.99" "02953.90" "01929.08" "01599.20" "39120.18" "02952.91" "01919.95"

**Comment by sebastian-c** [comment]
According to [this CPC document](http://unstats.un.org/unsd/cr/downloads/CPCv2.1_complete%28PDF%29_English.pdf), these values are dried fruits, forage products, bran, hides, and generally minor products.

**Comment by sebastian-c** [comment]
I've confirmed that the commas have been removed from the CPC conversion. However, in 2009, the following CPC codes are definitely not in the table (or any other that I can find):

> 21419.99 01241.90 01919.96 21419.91 39120.91 02959.99 01929.08 01599.20 01919.95 39120.18 02952.91 02953.90

**Comment by chrmongeau** [comment]
@sebastian-c All the codes reported above are available in the destination table, IIUC. Was this solved or the issue needs something else to be closed?

**Comment by sebastian-c** [comment]
I just checked and all the codes are indeed in the destination table. Next time I report an issue like this, I'll include some of the code I'm using to make it more obvious when the error is fixed.
