### ISSUE TITLE
Reporting in $, even if final solution will be in k$

### ISSUE THREAD

**Issue by marcosmilzo** [SWS-Methodology/faoswsTrade#27]
Related to JIRA ticket SWS-1405, the values will be reported in k$, but this is not available at the moment. So we are using $, and as soon as the problem is solve we go back to k$

**Comment by sebastian-c** [comment]
This JIRA ticket has been resolved.

**Comment by marcosmilzo** [comment]
This 00db22f8550bb15a3113d22e48db068993f70490 as well close #27.
