### ISSUE TITLE
Problem of flags for mirroring quantities and values

### ISSUE THREAD

**Issue by marcosmilzo** [SWS-Methodology/faoswsTrade#28]
Different flags when mirroring:
- since quantity, when they are mirrored for non-reporting countries, are not changing, the flag of the Status has to be the same as the flag for which it mirrors, while the method flag has to be "c"
- for values, the change of the flags is as it is: status "I", methodology "e"

**Comment by marcosmilzo** [comment]
Sebastian spotted some flags are " , ". This should not happen. I will further investigate

**Comment by sebastian-c** [comment]
More specifically, both flag values are blank,

**Comment by marcosmilzo** [comment]
After discussion with Carola about the flags. In case of official data the Status flag should be blank, while the methodology should be "h", which stand for harvested. This still needs to be done.

**Comment by chrmongeau** [comment]
A complete rewrite of the flag management was implemented.
