### ISSUE TITLE
Loading of dataset into the SWS

### ISSUE THREAD

**Issue by marcosmilzo** [SWS-Methodology/faoswsTrade#3]
Waiting for Giorgio to upload them

**Comment by sebastian-c** [comment]
For reference, in JIRA, this is SWS-1309.

**Comment by sebastian-c** [comment]
I think that Giorgio has loaded all the datasets. Can you confirm?

**Comment by marcosmilzo** [comment]
No, they are not all loaded, and anyway it is better to test them one by one, to make sure everything works fine. Still working with Giorgio about it

**Comment by sebastian-c** [comment]
The following datasets were just added:
- unsdpartners
- fclunits
- comtradeunits
- eur_conversion_usd

The following are still missing
- unsdpartnersblocks

**Comment by marcosmilzo** [comment]
Any news on the unsdpartnerblocks dataset?
By the way this data were using as well to convert from comtrade to FAO country code in the different steps. Then if we work with M49 codes this might not be anymore needed.

**Comment by sebastian-c** [comment]
I was about to file an issue about that missing dataset, are you suggesting that I shouldn't file it?

**Comment by sebastian-c** [comment]
Filed SWS-1361

**Comment by sebastian-c** [comment]
This issue has been closed, I need to check it

**Comment by sebastian-c** [comment]
Confirming that `unsdpartnersblocks` is on Early Access, but not yet on QA.

**Comment by sebastian-c** [comment]
Still not on QA. I'll make sure that it gets transferred. See SWS-1420

**Comment by chrmongeau** [comment]
Can we close this or is something still pending? (`unsdpartnersblocks` is on QA; see also comment on #24)

**Comment by sebastian-c** [comment]
This is now not pending and so can be closed.
