### ISSUE TITLE
NAs in reporters and partners (M49)

### ISSUE THREAD

**Issue by marcosmilzo** [SWS-Methodology/faoswsTrade#34]
This is related with the problem of NAs in reporters and partners while writing in the SWS.
There is a case in which NAs are generated because the FAO country code is 252 (non specific country) and we have to filter them, probably (still need to discuss with Carola).
But other countries have not been mapped properly.
This has to be checked in the SWS

**Comment by sebastian-c** [comment]
For 2009, as far as I can tell - the only issue is 252.

**Comment by marcosmilzo** [comment]
Correct. Still need to check with Carola if these should be removed or not. I think they are important in the total trade. I will update the issue as soon as I have a feedback.

**Comment by sebastian-c** [comment]
At the moment, code 252 is hardcoded to be removed from `esdata`.

**Comment by chrmongeau** [comment]
A temporary solution is to map FAO code 252 to 896 as suggested by Team BC. A proper decision of the final code has to be taken in a later moment.

**Comment by chrmongeau** [comment]
252 was mapped to 896, so it won't be removed from bilateral transactions as it is relatively important for total trade, as mentioned previously.
