### ISSUE TITLE
Non-standard application of the notes

### ISSUE THREAD

**Issue by marcosmilzo** [SWS-Methodology/faoswsTrade#35]
We faced the problem of too big data for trade USA wheat.
After clarification with team B/C we understood that the problem is that in the past UNSD was reporting, sometimes, data in tonnes, while nowadays just in kg.
For this reason a special check on the notes has to be done, in order to avoid to apply double conversions.

**Comment by marcosmilzo** [comment]
Hardcoded removal of notes for USA wheat (solution from Carola)

I will remove in the script, but additional analyses have to be performed.

```
NA     2 1001100090    NA      NA   1000    NA    NA      NA      231
NA     2 1001902015    NA      NA   1000    NA    NA      NA      231
NA     2 1001902055    NA      NA   1000    NA    NA      NA      231
```

**Comment by marcosmilzo** [comment]
There are 1726 (2% of the entire dataset of notes) other examples, among all years and all countries, with the similar type of adjustment as in the previous case, weight*1000.

**Comment by sebastian-c** [comment]
I found some cases for the US in 2011 with values over 1 billion (For reference, the EU produces 157 million tonnes of wheat a year):

```
   geographicAreaM49 timePointYears measuredItemCPC measuredElementTrade       Value flagObservationStatus
1:               840           2011            0114                 5910  3352435902                     I
2:               840           2011            0141                 5910 34231624310                     I
3:               840           2011        01919.96                 5910  3917921695                     I
4:               840           2011        39130.04                 5910  2227736787                     I
5:               840           2011           39160                 5910  7642811216                     I
```

**Comment by sebastian-c** [comment]
I did a little further searching in 2011. In most cases, a country appears more than once in the table, but there are few countries  with this issues. It seems distributed fairly evenly between imports and exports:

```
                 measuredElementTrade
geographicAreaM49 5610 5910
              170    1    0
              32     0    8
              356    2    7
              376    2    0
              404    1    0
              454    1    1
              484    8    3
              508    0    1
              554    1    1
              704    1    0
              710    1    5
              840    0    5
```

**Comment by chrmongeau** [comment]
The application of "notes" was removed: they were created on other data source (national files) and after many layers of notes, there was not an easy way to recover specific notes.
