### ISSUE TITLE
Narrow down list of processable HS codes in getAgriHScodes() by replacing HSagric_filter with HS2012-6 digits Standard

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#66]
Currently to filter HS codes of interest  in [getAgriHScodes](https://github.com/SWS-Methodology/faoswsTrade/blob/3538ee5b533b30cc57fb5d3f578d96413429e742/R/getAgriHSCodes.R) we use list of HS ranges from [HSagric_filter.xls](https://github.com/SWS-Methodology/hsfclmap/blob/eb2bc552fcce321b3dd7bc8655b092bc7a428e1e/data-raw/HSagric_filter.xls).

There is another source of HS codes: _HS2012-6 digits Standard.xls_ provided by B/C team. Currently we have three versions of it. [HS2012-6 digits Standard.xls](https://github.com/SWS-Methodology/hsfclmap/blob/eb2bc552fcce321b3dd7bc8655b092bc7a428e1e/data-raw/HS2012-6%20digits%20Standard.xls) in `hsfclmap` repository. It was presented by Claudia in last December and contains 1062 rows.

Two others are [HS2012-6 digits Standard_new.xlsx](https://github.com/SWS-Methodology/faoswsTrade/blob/3538ee5b533b30cc57fb5d3f578d96413429e742/data-raw/HS2007-6%20digits%20Standard_new.xlsx) with 1053 rows (including 10 NA HS codes) and [HS2012-6 digits Standard_new2.xlsx](https://github.com/SWS-Methodology/faoswsTrade/blob/3538ee5b533b30cc57fb5d3f578d96413429e742/data-raw/HS2007-6%20digits%20Standard_new2.xlsx) with same number of rows but without NA codes. Both of them were uploaded by @marcogarieri on April 5, 2016. 

Looks like the file is being updated by B/C team. So it is better to organize more efficient way of getting of new HS codes from B/C team. Either to ask B/C team to send us the file each time it has been updated.

**Comment by malexan** [comment]
@chrMongeau, do I understand correctly currently trade module filters raw data by chapters only?

Do you see any problems if I modify `getAgriHSCodes()` to use recent list of HS codes from B/C and add filtering of all input raw data by these codes?

**Comment by chrmongeau** [comment]
> do I understand correctly currently trade module filters raw data by chapters only?

Yes, @malexan, you are right: the module takes everything under given chapters.

> Do you see any problems if I modify getAgriHSCodes() to use recent list of HS codes from B/C and add filtering of all input raw data by these codes?

AFAICT, there should be no problem.

**Comment by malexan** [comment]
I've added the dataset with hs6 of interest, but haven't updated documentation for data.R as I don't have `faosws` package installed and `devtools::document()` failed.

**Comment by malexan** [comment]
As raw data sets in SWS do not have a column with HS codes of length 6, we can't simply ask SWS to return a subset of records based on a list of HS6 codes. There are two options:

1. Make truncation of HS+ codes with SQL on SWS side. I suspect such SQL quiry is not possible to wrap into `faosws::ReadDatatable`, so it would require manual intervention. But here we reduce time of data transferring (probably this time economy will be reduced to zero by truncate operation).
2. Copy full data sets in R (filtered only by chapters) and do HS codes truncation and filtering by R.

So I choose the second option as there are no significant benefits in the first option.

**Comment by malexan** [comment]
@chrMongeau, in case our HS code is length of, let's say, 4. Should we drop such record and take into account only codes of length 6 at least?

**Comment by malexan** [comment]
So currently I drop everything shorter than 6: [main.R](https://github.com/SWS-Methodology/faoswsTrade/blob/af8192ab5d4eee6a32f2c74f9ee846b280589a9b/modules/complete_tf_cpc/main.R#L280-L287) (It is a separate branch).

**Comment by chrmongeau** [comment]
@malexan Are [this](https://github.com/SWS-Methodology/faoswsTrade/blob/67f8570b788103691cc47daa3b53160a427153ce/modules/complete_tf_cpc/main.R#L302) and [this](https://github.com/SWS-Methodology/faoswsTrade/blob/67f8570b788103691cc47daa3b53160a427153ce/modules/complete_tf_cpc/main.R#L443) the most recent versions of the code in the [hs6agrifilter#66](https://github.com/SWS-Methodology/faoswsTrade/tree/hs6agrifilter%2366) branch? If they are, can we delete that branch?

**Comment by malexan** [comment]
Yep.
