### ISSUE TITLE
Optimize R/preAggregateMultipleTLRows.R

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#74]
We have [there](https://github.com/SWS-Methodology/faoswsTrade/blob/a08b3234ea6f38cde03c7a5398160873c6580071/R/preAggregateMultipleTLRows.R#L30-L60) four similar chunks of code, where only filtering variables are changed.

Could we change filtering to grouping by adding ` ~is.na(qty), ~is.na(weight)` to the group and do everything in one step?

**Comment by malexan** [comment]
What do you think, @chrMongeau?

Please check [my variant](https://github.com/SWS-Methodology/faoswsTrade/commit/089ce387276dfa5fa64e09a44c6da3ae3342320b).

**Comment by malexan** [comment]
The idea is:

```r
df <- tibble::tribble(
  ~qty, ~weight,
  NA,   NA,
  NA,   1,
  1,    NA,
  1,    1
)


df %>% 
  group_by(qtyisna = is.na(qty), 
           weightisna = is.na(weight)) %>% 
  summarise_at(c("qty", "weight"), sum) %>% 
  ungroup

# A tibble: 4 × 4
  qtyisna weightisna   qty weight
    <lgl>      <lgl> <dbl>  <dbl>
1   FALSE      FALSE     1      1
2   FALSE       TRUE     1     NA
3    TRUE      FALSE    NA      1
4    TRUE       TRUE    NA     NA
```

**Comment by malexan** [comment]
Also I suggest to move instruction to drop `chapter` out of this function as logically this operation is not part of aggregating of TL rows. And it would be difficult to understand for a newcomer why `chapter` suddenly disappeared.

**Comment by chrmongeau** [comment]
Yes, that seems the way this should have been done since the beginning (though it seems slower).

**Comment by chrmongeau** [comment]
Oh, and about dropping the chapter, I think you are right: it should be more transparent.

**Comment by chrmongeau** [comment]
@malexan I just added your solution directly into master (see 67f8570). I didn't pass through merging the issue74 branch as it was behind master with conflicts, so it was easier to modify it directly. Thanks. (When it is OK for you, you can proceed to delete the issue74 branch.)

**Comment by chrmongeau** [comment]
@malexan After merging the modification into master, I reverted the code to a version I had on a (local) branch. The reason is that (as I told you in a previous comment) there was a problem with speed. See below a comparison. (I'll delete the issue74 branch.)

```r
preAggregateMultipleTLRows1 <- function(rawdata = NA) {

  if (missing(rawdata)) stop('"rawdata" is required')

  raw <- rawdata %>%
    tbl_df() %>%
    mutate(no_quant  = is.na(qty),
           no_weight = is.na(weight),
           nrows = 1)

  raw$cases <- case_when(
                         !raw$no_quant & !raw$no_weight ~ 1L,
                         !raw$no_quant &  raw$no_weight ~ 2L,
                          raw$no_quant & !raw$no_weight ~ 3L,
                          raw$no_quant &  raw$no_weight ~ 4L
                         )
  raw %>%
        group_by(tyear, rep, prt, flow, comm, qunit, cases) %>%
        summarise_each_(
                        funs(sum(.)),
                        vars = c('weight', 'qty', 'tvalue', 'nrows')) %>%
        ungroup() %>%
        select(-cases)
}


preAggregateMultipleTLRows2 <- function(rawdata = NULL) {

  if (is.null(rawdata)) stop('"rawdata" is required')

  rawdata %>%
    tbl_df %>%
    # qty and weight seem to be always >0 or NA
    # no missing value
        group_by_(~tyear, ~rep, ~prt,
                  ~flow, ~comm, ~qunit,
                  no_quant = ~is.na(qty),
                  no_weight = ~is.na(weight)) %>%
        summarise_at(
          c("weight", "qty", "tvalue"), sum) %>%
        ungroup
}

mic <- microbenchmark(
  tldata1 <- preAggregateMultipleTLRows1(rawdata = tldata),
  tldata2 <- preAggregateMultipleTLRows2(rawdata = tldata),
  times = 10)
```

```
mic
Unit: seconds
                                                     expr       min        lq      mean    median        uq       max neval
 tldata1 <- preAggregateMultipleTLRows1(rawdata = tldata)  16.97384  17.16643  17.48235  17.24983  17.78614  18.54232    10
 tldata2 <- preAggregateMultipleTLRows2(rawdata = tldata) 226.88399 226.93798 228.50786 227.46976 229.03069 233.85274    10
```
