### ISSUE TITLE
faosws::GetCodeList column(s) not found: dimension

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#75]
It is with local version of faosws.

This is the rds with datatable of interest:

```r
> readRDS("/mnt/storage/faodata/codelist_trade-completed_tf_fcl_m49.rds")
      code              description selectionOnly type startDate endDate
   1: 9999            List Of Lists         FALSE    0        NA      NA
   2: 9994          Items By Domain         FALSE    0        NA      NA
   3: 9993            List Of Items         FALSE    0        NA      NA
   4: 9992               Item Trees         FALSE    0        NA      NA
   5: 9991 Agricultural Productions         FALSE    0        NA      NA
  ---
1350:   16           Flour of Wheat         FALSE    3        NA      NA
1351:   15                    Wheat         FALSE    2        NA      NA
1352:   10  Total Merchandise Trade         FALSE    3        NA      NA
1353:    5    Current Conv. Factors         FALSE   18        NA      NA
1354:    1               Population         FALSE    1        NA      NA
```

Then faoswsTrade::descFCL -> faosws::GetCodeList

```r
> swsdomain = "trade"
> swsdataset = "completed_tf_fcl_m49"
> swsdimension = "measuredItemFS"
>
> faosws::GetCodeList(swsdomain,
+                     swsdataset,
+                     swsdimension)
Error in `[.data.table`(d, , "dimension", with = F) :
  column(s) not found: dimension
```
faosws version: 0.8.2.9901

**Comment by malexan** [comment]
@chrMongeau:

I got this problem too when I was trying to run the module from home during
+December: I got around the problem by removing fcldesc from:

```r
fcl_spec_mt_conv <- tldata %>%
  filter_(~fclunit == "mt" & is.na(weight) & conv == 0) %>%
  select_(~fcl, ~wco) %>%
  distinct() %>%
  mutate_(fcldesc = ~descFCL(fcl))
```

so that it became:

```r
fcl_spec_mt_conv <- tldata %>%
  filter_(~fclunit == "mt" & is.na(weight) & conv == 0) %>%
  select_(~fcl, ~wco) %>%
  distinct()
```

**Comment by malexan** [comment]
And then to remove it later:

```r
  ### Add commodity specific conv.factors to dataset

  tldata <- tldata %>%
    left_join(fcl_spec_mt_conv %>%
                select_(~-fcldesc),
              by = c("fcl", "wco"))
```
Right? Than I remove both these pieces in master?

**Comment by malexan** [comment]
@sebastian-c Could you look at the problem, please.

**Comment by sebastian-c** [comment]
Yeah, I think something's wrong with your table format. That might be my fault. I wrote in the documentation:

> NOTE: For this offline version, an rds file of the format domain-dataset.rds is required. It must be identical to the output of GetCodeList, but with an additional column on the far left 'dimension' which is a character column of the dimension name.

You need an extra column on the left indicating the name of the dimension.

**Comment by malexan** [comment]
Bad habit of not reading manuals :) Maybe an additional check for such column in the offline version?

What do you think if to create helper function to extract from SWS and to prepare such data sets for the offline version? I don't like the idea of manual tweaks of these data sets. Also it would be useful for quick update when data sets are changed in SWS.

**Comment by sebastian-c** [comment]
There is a function for that. It's an unexported function called `MakeCodeListRds`. It asks that your real faosws package be called `faosws2` so that you can connect to the system.
