### ISSUE TITLE
Move alignHSLength() and selection from multiple FCL results out from hsInRange() to make it easier to debug and to report

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#80]
[Currently](https://github.com/SWS-Methodology/faoswsTrade/blob/ddd6edea6c6b7824e91a322bce960f59d2412a43/R/hsInRange.R) the function `hsInRange()` includes two additional procedures plus to key purpose of searching for suitable HS-ranges:

* aligning of lengths of HS codes
* choosing of an FCL code in case there are multiple matches

In #79 we found out a potential problem in the process of length aligning. To debug it faster and to have better module layout we suggest to put these three procedures at one level.

**Comment by malexan** [comment]
* `mapHS2FCL`: parent HS->FCL mapping function:
  - 'alignHSLength`: align lengths of HS codes in data and in the mapping table;
  - `hsInRange`: find all matches;
  - `sel1FCL`: select one record from multiple matches.

The parent function should take reporter, hs, flow and mapping table. Or usual trade dataset with obligatory columns and mapping table dataset.

**Comment by chrmongeau** [comment]
@malexan There is currently a branch called [#80splithsinrange](https://github.com/SWS-Methodology/faoswsTrade/tree/%2380splithsinrage), but the issue that it is referring to is closed. Can we delete that branch?

**Comment by chrmongeau** [comment]
@malexan Sorry, I answer my own question: I just saw in #82 that it was merged successfully. I'll proceed to delete the branch.
