### ISSUE TITLE
Per country reporting on raw input trade data

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#84]
To implement [the request](https://github.com/SWS-Methodology/faoswsTrade/issues/67#issuecomment-281312959).

# Quality of data

1. Total number of records.
2. Count of no quantity/no value/non-numeric records
3. Proportion of no quantity/no value records

# HS codes

1. Length of HS codes

**Comment by chrmongeau** [comment]
The generation of pre-processing reports were incorporated in the code. The [pre_processing_report](https://github.com/SWS-Methodology/faoswsTrade/tree/5194411f0f8541d9377a447f30aee41ea1a47e35/modules/pre_processing_report) plugin was developed for creating the timeseries of the reports and save them on SWS as datatables.
