### ISSUE TITLE
adaptTradeDataNames does more than it promises

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#88]
1. Function's name and description say it only standardizes column names but additionally it makes types conversion.
2. The function converts area codes to double (numeric) type for Eurostat but to integer type for Tariffline. Also it explicitly converts `value`, `weight` and `qty` to numeric type for Tariffline and doesn't touch these column in Eurostat.

I suggest to move type conversions to a separate function to make it more transparent. I would like to use `adaptTradeDataNames` as early as possible: it will allow to use universal function for raw data quality reporting. 

For area codes I would use integer type as it is enough here (maximum code is 866).

```
> glimpse(esdata)
Observations: 1,994,386
Variables: 9
$ reporter <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
$ partner  <dbl> 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 8, 9, 10, 10, 11, 11, 11...
$ hs       <chr> "02045019", "05010000", "20089924", "52061100", "04063...
$ flow     <int> 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, ...
$ year     <chr> "2014", "2014", "2014", "2014", "2014", "2014", "2014"...
$ value    <dbl> 0.40, 0.01, 0.02, 0.07, 0.03, 0.02, 0.30, 0.15, 0.00, ...
$ weight   <dbl> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
$ qty      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 12...
$ hs6      <chr> "020450", "050100", "200899", "520611", "040630", "200...
```

```
> tldata <- adaptTradeDataNames(tradedata = tldata, origin = "TL")
> glimpse(tldata)
Observations: 742,598
Variables: 10
$ reporter <int> 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124,...
$ partner  <int> 10, 10, 100, 100, 100, 100, 100, 100, 100, 100, 100, 1...
$ hs       <chr> "150420", "381190", "030616", "040630", "040690", "040...
$ flow     <int> 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
$ year     <chr> "2014", "2014", "2014", "2014", "2014", "2014", "2014"...
$ value    <dbl> 2.151210e+05, 2.432266e+02, 2.468882e+03, 1.085223e+01...
$ weight   <dbl> 34496, 57, 200, 4, 182468, 10491, 1566, 16232, 384, 2,...
$ qty      <dbl> 34496, 57, 200, 4, 182468, 10491, 1566, 16232, 384, 2,...
$ qunit    <int> 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, ...
$ hs6      <chr> "150420", "381190", "030616", "040630", "040690", "040...
> 
```

**Comment by malexan** [comment]
A solution for renaming without duplication of names:

```r
oldnames <- c("Sepal.Length", "Species")
newnames <- c("len", "spec")

iris %>% 
  rename_(.dots = setNames(oldnames, newnames)) %>% glimpse
```
```
Observations: 150
Variables: 5
$ len          <dbl> 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8, 4...
$ Sepal.Width  <dbl> 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0, 3...
$ Petal.Length <dbl> 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1...
$ Petal.Width  <dbl> 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0...
$ spec         <fctr> setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, s...
```

**Comment by chrmongeau** [comment]
> I suggest to move type conversions to a separate function to make it more transparent.

8bbbe65 tried to fix this, at least for `tldata`. With `esdata` we have some non-numeric strings that produce NAs if `adaptTradeNames()` is used (as it changes variable types). An option would be to have an `adaptTradeVariableTypes()` (or something like that) to be used along with `adaptTradeNames()`, but I'll leave the decision to @malexan given that he wants `adaptTradeNames()` used as soon as possible (which makes sense).

The rest of the things were already resolved, so I think this can be closed.

**Comment by malexan** [comment]
> The rest of the things were already resolved, so I think this can be closed.

The function still does more than promises :) So let me work on it.
