### ISSUE TITLE
Unstable format of HS codes in the mapping table (from MDB files)

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#91]
While dealing with #79 and #85 I returned again to the problem of a format what is used in MDB files for storing of HS codes (`fromcode` and `tocode` columns).

Theoretically all HS codes must be of odd length for chapters 1-9 and of even length for chapter 10 and above. The reason for this is that every HS level consists of two digits (taking chapters 1-9 with leading zero: 01, 02,... 09). 

Eurostat data consists of CN/HS codes of length 8. Situation is more difficult with Tariffline data, but still we observe strong tendency towards even-length codes. Share of any odd-length code is less than 1 percent. Code length in the mapping table follows the trend except length 9, its share is 3.9%.

30% of all HS codes in the mapping table absent in the list of targeted agricultural codes. Probably some of them represent fishery, but some could have wrongly placed leading zero. Latter idea is not supported by numbers: without removing leading zeros we get 261940 records with "illegal" codes, when with removing - 484209 records. These codes can be removed from HS->FCL mapping table to decrease computation time.

```r
> esdata %>% 
+     select(product_nc) %>% 
+     mutate(codelength = str_length(product_nc)) %>% 
+     group_by(codelength) %>% 
+     summarize(n = n())
# A tibble: 2 × 2
  codelength       n
       <int>   <int>
1          2  165051
2          8 2332996

> tldata %>% 
+     select(comm) %>% 
+     mutate(codelength = str_length(comm)) %>% 
+     group_by(codelength) %>% 
+     summarize(count = n()) %>% 
+     ungroup %>% 
+     mutate(prop = scales::percent(count / sum(count)))
# A tibble: 8 × 3
  codelength   count  prop
       <int>   <int> <chr>
1          2    2818  0.1%
2          4     200  0.0%
3          6 1004136 28.0%
4          7       6  0.0%
5          8 2247837 62.6%
6          9   14517  0.4%
7         10  317694  8.8%
8         11    3580  0.1%

> hsfclmap3 %>% 
+     select(fromcode) %>% 
+     mutate(codelength = str_length(fromcode)) %>% 
+     group_by(codelength) %>% 
+     summarize(count = n()) %>% 
+     ungroup %>% 
+     mutate(prop = scales::percent(count / sum(count)))
# A tibble: 11 × 3
   codelength  count  prop
        <int>  <int> <chr>
1           2      3  0.0%
2           3    121  0.0%
3           4    841  0.1%
4           5   6003  0.7%
5           6 143022 16.6%
6           7   3990  0.5%
7           8 450831 52.3%
8           9  33708  3.9%
9          10 220538 25.6%
10         11   3236  0.4%
11         12     36  0.0%

> hsfclmap3 %>% 
+     select(fromcode) %>% 
+     mutate(hs6 = as.integer(str_sub(fromcode, end = 6L)),
+            legalhs = hs6 %in% as.integer(getAgriHSCodes())) %>% 
+     filter(!legalhs) %>% nrow
[1] 261940
> hsfclmap3 %>% 
+     select(fromcode) %>% 
+     mutate(
+       fromcode = str_replace(fromcode, "^0*", ""),
+       hs6 = as.integer(str_sub(fromcode, end = 6L)),
+       legalhs = hs6 %in% as.integer(getAgriHSCodes())) %>% 
+     filter(!legalhs) %>% nrow
[1] 484209

```

**Comment by carola-f** [comment]
Few countries use odd-digit code length (examples are Rwanda and Sri Lanka with 7 digits and Taiwan with 11 digits), but they must be kept and catered for by the system.
The first validation tests show a systematic underestimation of total trade by the new module. 
The possibility exists that the module excludes some codes and therefore underestimates trade.

**Comment by malexan** [comment]
> Few countries use odd-digit code length (examples are Rwanda and Sri Lanka with 7 digits and Taiwan with 11 digits), but they must be kept and catered for by the system.

OK, it is supported by our current model: it doesn't take into account odd/even digit code length. It simply adds zeros (nines for `tocode` column) on the right side of code to align length of codes between trade data and the mapping table. 

To count the length of HS codes we use original character format what includes leading zeros. 

My doubt is that if some HS codes in the mapping table accidentally don't have zeros it leads to incorrect calculations of HS length. I still don't have proper statistic on it (too many degrees of freedom for the problem), but it bothers me.

**Comment by carola-f** [comment]
Before developing any automatic solution, we need validation/feedback from the users. Can you prepare a table with the main findings to be shared with the Trade data tea? The table should contain the list of countries for which you found several codes lengths (reporting country code, reporting country code, HS length, number and percentage of observations)

**Comment by malexan** [comment]
> Can you prepare a table...

Yes, I will. It is almost in the report.
