### ISSUE TITLE
Modify mapHS2FCL() so that it just creates the mapping

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#94]
I think that it would be better to modify `mapHS2FCL()` so that it produces the mapping, without joining it to the dataset. I'm saying this because the mapping generation is a process that needs time and in local runs it could be better to have a previously generated mapping table without the need to run again `mapHS2FCL()`. Joining the mapping table to the dataset should be left outside the function.

**Comment by chrmongeau** [comment]
I just run on tldata and it took a very long time (did not take note on time, but I think it was at least one hour). Moreover, I got this at the end:

```
1: In max(stringr::str_length(mapdataset$fromcode)) :
  no non-missing arguments to max; returning -Inf
2: In max(stringr::str_length(mapdataset$tocode)) :
  no non-missing arguments to max; returning -Inf
```

It seems that they are not errors, but in any case I report them.

**Comment by malexan** [comment]
> It seems that they are not errors, but in any case I report them.

Christian, could you open a separate issue for it, as this error doesn't concern the structure of `mapHS2FCL`?

**Comment by malexan** [comment]
>  to modify mapHS2FCL() so that it produces the mapping, without joining it to the dataset

My idea was to hide those joins from `main.R`. :) Let me think about this.

>  Joining the mapping table to the dataset should be left outside the function.

And what about extraction of unique report/flow/hs combinations from trade data set? Should it be done inside of `mapHS2FCL`? Do you want to pass to the function full data set either the combinations?

**Comment by chrmongeau** [comment]
> My idea was to hide those joins from main.R. :) Let me think about this.

I was referring just to the [last one](https://github.com/SWS-Methodology/faoswsTrade/blob/aeca6993f2ea235b97dd335ab713acf0d02cb165/R/mapHS2FCL.R#L60-L61). For instance, in a previous version of the module we had `esdatalinks` and `tldatalinks`, and I saved them so that if I had to run the module again (and I did) i didn't have to go through all the process of generating the mapping.

**Comment by chrmongeau** [comment]
> the mapping generation is a process that needs time

Confirmed. On my machine I got `mapHS2FCL()` to run relatively fast on `esdata`, but terribily slow on `tldata` (time in 24h format):

* `esdata`
  - start time: 15:33:00
  - end time: 15:38:45
* `tldata`
  - start time: 15:43:00
  - end time: 16:33:49

Note: as reported in #97, I'm setting `multicore` to FALSE as setting it to TRUE causes an error.
