### ISSUE TITLE
Do we need RMarkdown heading in main.R?

### ISSUE THREAD

**Issue by malexan** [SWS-Methodology/faoswsTrade#98]
Christian, do we need [all those lines](https://github.com/SWS-Methodology/faoswsTrade/blob/0641453d083852c281b5818f63c3f66eb3825502/modules/complete_tf_cpc/main.R#L1-L34) with RMarkdown stuff in the main.R? I removed them earlier, then you returned them back :) I thought it was legacy from original Markdown document what Marco used to compile the module. 

I don't have those lines in `extendreport` branch, so I need to decide which version should I keep while merging.

**Comment by chrmongeau** [comment]
Yes, those lines are needed. It was decided to have a documentation for the modules that follows the flow process, by using inline rmarkdown code  (for reference, have a look at the email massages on 2016-11-10 and 2016-11-14). This kind of documentation is meant to be a step-by-step explanation of the operations carried out in the module, which complements a more ["narrative" documentation](https://github.com/SWS-Methodology/faoswsTrade/blob/master/vignettes/Documentation/tradeDocumentation.pdf) (thus, the former document is more like an "appendix").

The documentation can be generated by using `rmarkdown::render("main.R")`. Right now it complains about something: see #99 (not critical right now).
